// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: smartwatch

#ifndef UI_SCREENHOME_H
#define UI_SCREENHOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenHome
extern void ui_ScreenHome_screen_init(void);
extern void ui_ScreenHome_screen_destroy(void);
extern void ui_event_ScreenHome(lv_event_t * e);
extern lv_obj_t * ui_ScreenHome;
extern lv_obj_t * ui_ImgHomeBackground;
extern lv_obj_t * ui_LabelDate1;
extern lv_obj_t * ui_HomeTimeLabel;
extern lv_obj_t * ui_dots;
extern lv_obj_t * ui_HomeDateLabel;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_HomeWeatherTempLabel;
extern lv_obj_t * ui_HomeWeatherStateLabel;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_HomeBatteryLabel;
extern lv_obj_t * ui_AnalogClock;
extern lv_obj_t * ui_HomeSecondHand;
extern lv_obj_t * ui_HomeMinuteHand;
extern lv_obj_t * ui_HomeHourHand;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_HomeTempLabel;
extern lv_obj_t * ui_Label1temp;
extern lv_obj_t * ui_HomeHumidityLabel;
extern lv_obj_t * ui_Label1hum;
extern lv_obj_t * ui_HomeStepLabel;
extern lv_obj_t * ui_Label1step;
extern lv_obj_t * ui_BottomNav;
extern void ui_event_BtnNavCall(lv_event_t * e);
extern lv_obj_t * ui_BtnNavCall;
extern lv_obj_t * ui_Label16;
extern void ui_event_BtnNavSport(lv_event_t * e);
extern lv_obj_t * ui_BtnNavSport;
extern lv_obj_t * ui_Label2;
extern void ui_event_BtnNavHealth(lv_event_t * e);
extern lv_obj_t * ui_BtnNavHealth;
extern lv_obj_t * ui_Label18;
extern void ui_event_BtnNavWeather(lv_event_t * e);
extern lv_obj_t * ui_BtnNavWeather;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

