// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: smartwatch

#include "../ui.h"

lv_obj_t * ui_ScreenHealth = NULL;
lv_obj_t * ui_Image22 = NULL;
lv_obj_t * ui_HealthTopCard = NULL;
lv_obj_t * ui_HeartInfoPanel = NULL;
lv_obj_t * ui_Image23 = NULL;
lv_obj_t * ui_HeartValueLabel = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_HeartStateLabel = NULL;
lv_obj_t * ui_HeartRangeLabel = NULL;
lv_obj_t * ui_HeartImage = NULL;
lv_obj_t * ui_bpmzhi = NULL;
lv_obj_t * ui_HeartSpinner = NULL;
lv_obj_t * ui_BloodOxygenPanel = NULL;
lv_obj_t * ui_bleed1 = NULL;
lv_obj_t * ui_blood_fill = NULL;
lv_obj_t * ui_bleed2 = NULL;
lv_obj_t * ui_HeartChartPanel = NULL;
lv_obj_t * ui_HeartChart = NULL;
lv_obj_t * ui_shijain1 = NULL;
lv_obj_t * ui_shujian2 = NULL;
lv_obj_t * ui_shijian3 = NULL;
lv_obj_t * ui_shijiansi = NULL;
lv_obj_t * ui_zong3 = NULL;
lv_obj_t * ui_shijian5 = NULL;
lv_obj_t * ui_zong2 = NULL;
lv_obj_t * ui_zong1 = NULL;
lv_obj_t * ui_zong0 = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_MAXnumLabel = NULL;
lv_obj_t * ui_MINNUMLabel = NULL;
lv_obj_t * ui_HealthMeasureBtn = NULL;
lv_obj_t * ui_MeasureBtnLabel = NULL;
lv_obj_t * ui_MeasureIconPanel = NULL;
// event funtions
void ui_event_ScreenHealth(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenHome_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenWeather, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScreenWeather_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        animhealthtopin_Animation(ui_HealthTopCard, 0);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        health_screen_unloaded_event(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        health_measure_btn_event(e);
    }
}

void ui_event_HealthMeasureBtn(
    lv_event_t *e)
{
    lv_event_code_t event_code;
    lv_obj_t *target;

    event_code =
        lv_event_get_code(e);

    target =
        lv_event_get_target(e);

    if (event_code ==
        LV_EVENT_VALUE_CHANGED)
    {
        if (lv_obj_has_state(
                target,
                LV_STATE_CHECKED))
        {
            /*
             * 避免反复点击后叠加多个动画。
             */
            lv_anim_del(
                ui_HeartImage,
                NULL
            );

            lv_anim_del(
                ui_bleed1,
                NULL
            );

            lv_anim_del(
                ui_bleed2,
                NULL
            );

            /*
             * 恢复动画起点。
             */
            lv_img_set_zoom(
                ui_HeartImage,
                256
            );

            lv_obj_set_x(
                ui_bleed1,
                -45
            );

            lv_obj_set_x(
                ui_bleed2,
                -38
            );

            /*
             * 开始测量时启动动画。
             */
            heart_Animation(
                ui_HeartImage,
                0
            );

            blood1_Animation(
                ui_bleed1,
                0
            );

            blood2_Animation(
                ui_bleed2,
                0
            );

            lv_label_set_text(
                ui_MeasureBtnLabel,
                "STOP MEASURING"
            );
        }
        else
        {
            /*
             * 停止测量后停止动画。
             */
            lv_anim_del(
                ui_HeartImage,
                NULL
            );

            lv_anim_del(
                ui_bleed1,
                NULL
            );

            lv_anim_del(
                ui_bleed2,
                NULL
            );

            /*
             * 恢复静止位置。
             */
            lv_img_set_zoom(
                ui_HeartImage,
                256
            );

            lv_obj_set_x(
                ui_bleed1,
                -45
            );

            lv_obj_set_x(
                ui_bleed2,
                -38
            );

            lv_label_set_text(
                ui_MeasureBtnLabel,
                "START MEASURING"
            );
        }

        /*
         * 保留原来的测量状态回调。
         */
        health_measure_toggle_cb(e);
    }
}

// build funtions

void ui_ScreenHealth_screen_init(void)
{
    ui_ScreenHealth = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenHealth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ScreenHealth, lv_color_hex(0x16D9E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScreenHealth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image22 = lv_img_create(ui_ScreenHealth);
    lv_img_set_src(ui_Image22, &ui_img_screen_background_320x240_png);
    lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HealthTopCard = lv_obj_create(ui_ScreenHealth);
    lv_obj_set_width(ui_HealthTopCard, 306);
    lv_obj_set_height(ui_HealthTopCard, 98);
    lv_obj_set_x(ui_HealthTopCard, -1);
    lv_obj_set_y(ui_HealthTopCard, -70);
    lv_obj_set_align(ui_HealthTopCard, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HealthTopCard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HealthTopCard, lv_color_hex(0x16D9E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HealthTopCard, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HealthTopCard, lv_color_hex(0x16D9E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HealthTopCard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeartInfoPanel = lv_obj_create(ui_HealthTopCard);
    lv_obj_set_width(ui_HeartInfoPanel, 148);
    lv_obj_set_height(ui_HeartInfoPanel, 76);
    lv_obj_set_x(ui_HeartInfoPanel, 66);
    lv_obj_set_y(ui_HeartInfoPanel, 0);
    lv_obj_set_align(ui_HeartInfoPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HeartInfoPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HeartInfoPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeartInfoPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HeartInfoPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HeartInfoPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image23 = lv_img_create(ui_HeartInfoPanel);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image23, -164);
    lv_obj_set_y(ui_Image23, 1);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HeartValueLabel = lv_label_create(ui_HeartInfoPanel);
    lv_obj_set_width(ui_HeartValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeartValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeartValueLabel, -26);
    lv_obj_set_y(ui_HeartValueLabel, -29);
    lv_obj_set_align(ui_HeartValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeartValueLabel, "78");
    lv_obj_set_style_text_color(ui_HeartValueLabel, lv_color_hex(0xF5F7FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HeartValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeartValueLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_HeartInfoPanel);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 13);
    lv_obj_set_y(ui_Label20, -24);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "bpm");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xA9B6C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeartStateLabel = lv_label_create(ui_HeartInfoPanel);
    lv_obj_set_width(ui_HeartStateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeartStateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeartStateLabel, -13);
    lv_obj_set_y(ui_HeartStateLabel, 0);
    lv_obj_set_align(ui_HeartStateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeartStateLabel, "Normal");
    lv_obj_set_style_text_color(ui_HeartStateLabel, lv_color_hex(0x39E58C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HeartStateLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeartStateLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeartRangeLabel = lv_label_create(ui_HeartInfoPanel);
    lv_obj_set_width(ui_HeartRangeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeartRangeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeartRangeLabel, -14);
    lv_obj_set_y(ui_HeartRangeLabel, 28);
    lv_obj_set_align(ui_HeartRangeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeartRangeLabel, "60~100");
    lv_obj_set_style_text_color(ui_HeartRangeLabel, lv_color_hex(0xA9B6C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HeartRangeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeartRangeLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeartImage = lv_img_create(ui_HeartInfoPanel);
    lv_img_set_src(ui_HeartImage, &ui_img_heart_png);
    lv_obj_set_width(ui_HeartImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeartImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeartImage, -59);
    lv_obj_set_y(ui_HeartImage, 28);
    lv_obj_set_align(ui_HeartImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HeartImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HeartImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bpmzhi = lv_label_create(ui_HeartInfoPanel);
    lv_obj_set_width(ui_bpmzhi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bpmzhi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bpmzhi, 38);
    lv_obj_set_y(ui_bpmzhi, 28);
    lv_obj_set_align(ui_bpmzhi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bpmzhi, "bpm");
    lv_obj_set_style_text_color(ui_bpmzhi, lv_color_hex(0xA9B6C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bpmzhi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bpmzhi, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeartSpinner = lv_spinner_create(ui_HealthTopCard, 1000, 90);
    lv_obj_set_width(ui_HeartSpinner, 98);
    lv_obj_set_height(ui_HeartSpinner, 90);
    lv_obj_set_x(ui_HeartSpinner, -79);
    lv_obj_set_y(ui_HeartSpinner, 1);
    lv_obj_set_align(ui_HeartSpinner, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HeartSpinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_border_width(ui_HeartSpinner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_HeartSpinner, lv_color_hex(0x5A1F2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_HeartSpinner, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_HeartSpinner, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_HeartSpinner, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_HeartSpinner, lv_color_hex(0xEE1C18), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_HeartSpinner, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_HeartSpinner, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_HeartSpinner, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BloodOxygenPanel = lv_obj_create(ui_HealthTopCard);
    lv_obj_set_width(ui_BloodOxygenPanel, 77);
    lv_obj_set_height(ui_BloodOxygenPanel, 77);
    lv_obj_set_x(ui_BloodOxygenPanel, -83);
    lv_obj_set_y(ui_BloodOxygenPanel, 0);
    lv_obj_set_align(ui_BloodOxygenPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BloodOxygenPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BloodOxygenPanel, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BloodOxygenPanel, lv_color_hex(0x390800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BloodOxygenPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_BloodOxygenPanel, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BloodOxygenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BloodOxygenPanel, lv_color_hex(0x4E2725), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BloodOxygenPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bleed1 = lv_img_create(ui_BloodOxygenPanel);
    lv_img_set_src(ui_bleed1, &ui_img_wave2_png);
    lv_obj_set_width(ui_bleed1, LV_SIZE_CONTENT);   /// 402
    lv_obj_set_height(ui_bleed1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bleed1, -45);
    lv_obj_set_y(ui_bleed1, -15);
    lv_obj_set_align(ui_bleed1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bleed1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bleed1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_blood_fill = lv_obj_create(ui_BloodOxygenPanel);
    lv_obj_set_height(ui_blood_fill, 55);
    lv_obj_set_width(ui_blood_fill, lv_pct(163));
    lv_obj_set_x(ui_blood_fill, -1);
    lv_obj_set_y(ui_blood_fill, 20);
    lv_obj_set_align(ui_blood_fill, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_blood_fill, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_blood_fill, lv_color_hex(0xDE615A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_blood_fill, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_blood_fill, lv_color_hex(0xDE1810), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_blood_fill, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_blood_fill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bleed2 = lv_img_create(ui_BloodOxygenPanel);
    lv_img_set_src(ui_bleed2, &ui_img_wave1_png);
    lv_obj_set_width(ui_bleed2, LV_SIZE_CONTENT);   /// 402
    lv_obj_set_height(ui_bleed2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bleed2, -38);
    lv_obj_set_y(ui_bleed2, -17);
    lv_obj_set_align(ui_bleed2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bleed2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bleed2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HeartChartPanel = lv_obj_create(ui_ScreenHealth);
    lv_obj_set_width(ui_HeartChartPanel, 306);
    lv_obj_set_height(ui_HeartChartPanel, 130);
    lv_obj_set_x(ui_HeartChartPanel, -2);
    lv_obj_set_y(ui_HeartChartPanel, 47);
    lv_obj_set_align(ui_HeartChartPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HeartChartPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HeartChartPanel, lv_color_hex(0x16D9E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeartChartPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HeartChartPanel, lv_color_hex(0x16D9E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HeartChartPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeartChart = lv_chart_create(ui_HeartChartPanel);
    lv_obj_set_width(ui_HeartChart, 261);
    lv_obj_set_height(ui_HeartChart, 49);
    lv_obj_set_x(ui_HeartChart, 6);
    lv_obj_set_y(ui_HeartChart, -27);
    lv_obj_set_align(ui_HeartChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_HeartChart, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_HeartChart, LV_CHART_AXIS_PRIMARY_Y, 0, 150);
    lv_chart_set_axis_tick(ui_HeartChart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, false, 50);
    lv_chart_set_axis_tick(ui_HeartChart, LV_CHART_AXIS_PRIMARY_Y, 0, 0, 5, 2, false, 50);
    lv_chart_set_axis_tick(ui_HeartChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 5, 2, false, 25);
    lv_chart_series_t * ui_HeartChart_series_1 = lv_chart_add_series(ui_HeartChart, lv_color_hex(0xFF4567),
                                                                     LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_HeartChart_series_1_array[] = { 62, 60, 64, 58, 68, 82, 74, 69, 76, 71, 84, 79, 92, 120, 98, 82, 75, 80, 68, 76, 70, 65, 58, 54, 52 };
    lv_chart_set_ext_y_array(ui_HeartChart, ui_HeartChart_series_1, ui_HeartChart_series_1_array);
    lv_obj_set_style_radius(ui_HeartChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HeartChart, lv_color_hex(0x071521), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeartChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HeartChart, lv_color_hex(0x164A63), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HeartChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HeartChart, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_HeartChart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_HeartChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_HeartChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_HeartChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_HeartChart, lv_color_hex(0x183246), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_HeartChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_HeartChart, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_line_width(ui_HeartChart, 3, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_rounded(ui_HeartChart, true, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_size(ui_HeartChart, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_shijain1 = lv_label_create(ui_HeartChartPanel);
    lv_obj_set_width(ui_shijain1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shijain1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shijain1, -114);
    lv_obj_set_y(ui_shijain1, 5);
    lv_obj_set_align(ui_shijain1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shijain1, "00:00");
    lv_obj_set_style_text_color(ui_shijain1, lv_color_hex(0xA9B6C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shijain1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shujian2 = lv_label_create(ui_HeartChartPanel);
    lv_obj_set_width(ui_shujian2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shujian2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shujian2, -55);
    lv_obj_set_y(ui_shujian2, 6);
    lv_obj_set_align(ui_shujian2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shujian2, "06:00");
    lv_obj_set_style_text_color(ui_shujian2, lv_color_hex(0xA9B6C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shujian2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shijian3 = lv_label_create(ui_HeartChartPanel);
    lv_obj_set_width(ui_shijian3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shijian3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shijian3, 9);
    lv_obj_set_y(ui_shijian3, 6);
    lv_obj_set_align(ui_shijian3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shijian3, "12:00");
    lv_obj_set_style_text_color(ui_shijian3, lv_color_hex(0xA9B6C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shijian3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shijiansi = lv_label_create(ui_HeartChartPanel);
    lv_obj_set_width(ui_shijiansi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shijiansi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shijiansi, 68);
    lv_obj_set_y(ui_shijiansi, 9);
    lv_obj_set_align(ui_shijiansi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shijiansi, "18:00");
    lv_obj_set_style_text_color(ui_shijiansi, lv_color_hex(0xA9B6C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shijiansi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zong3 = lv_label_create(ui_HeartChartPanel);
    lv_obj_set_width(ui_zong3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_zong3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_zong3, -139);
    lv_obj_set_y(ui_zong3, -50);
    lv_obj_set_align(ui_zong3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_zong3, "150");
    lv_obj_set_style_text_color(ui_zong3, lv_color_hex(0xA9B6C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_zong3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shijian5 = lv_label_create(ui_HeartChartPanel);
    lv_obj_set_width(ui_shijian5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shijian5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shijian5, 125);
    lv_obj_set_y(ui_shijian5, 8);
    lv_obj_set_align(ui_shijian5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shijian5, "24:00");
    lv_obj_set_style_text_color(ui_shijian5, lv_color_hex(0xA9B6C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shijian5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zong2 = lv_label_create(ui_HeartChartPanel);
    lv_obj_set_width(ui_zong2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_zong2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_zong2, -139);
    lv_obj_set_y(ui_zong2, -35);
    lv_obj_set_align(ui_zong2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_zong2, "100");
    lv_obj_set_style_text_color(ui_zong2, lv_color_hex(0xA9B6C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_zong2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zong1 = lv_label_create(ui_HeartChartPanel);
    lv_obj_set_width(ui_zong1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_zong1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_zong1, -136);
    lv_obj_set_y(ui_zong1, -21);
    lv_obj_set_align(ui_zong1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_zong1, "50");
    lv_obj_set_style_text_color(ui_zong1, lv_color_hex(0xA9B6C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_zong1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zong0 = lv_label_create(ui_HeartChartPanel);
    lv_obj_set_width(ui_zong0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_zong0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_zong0, -133);
    lv_obj_set_y(ui_zong0, -9);
    lv_obj_set_align(ui_zong0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_zong0, "0");
    lv_obj_set_style_text_color(ui_zong0, lv_color_hex(0xA9B6C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_zong0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_HeartChartPanel);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, 57);
    lv_obj_set_y(ui_Label28, -56);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "MAX");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_HeartChartPanel);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 110);
    lv_obj_set_y(ui_Label29, -55);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "Min");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MAXnumLabel = lv_label_create(ui_HeartChartPanel);
    lv_obj_set_width(ui_MAXnumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MAXnumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MAXnumLabel, 83);
    lv_obj_set_y(ui_MAXnumLabel, -56);
    lv_obj_set_align(ui_MAXnumLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MAXnumLabel, "120");
    lv_obj_set_style_text_color(ui_MAXnumLabel, lv_color_hex(0xFF4567), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MAXnumLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MAXnumLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MINNUMLabel = lv_label_create(ui_HeartChartPanel);
    lv_obj_set_width(ui_MINNUMLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MINNUMLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MINNUMLabel, 133);
    lv_obj_set_y(ui_MINNUMLabel, -54);
    lv_obj_set_align(ui_MINNUMLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MINNUMLabel, "52");
    lv_obj_set_style_text_color(ui_MINNUMLabel, lv_color_hex(0x1156CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MINNUMLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HealthMeasureBtn = lv_btn_create(ui_HeartChartPanel);
    lv_obj_set_width(ui_HealthMeasureBtn, 281);
    lv_obj_set_height(ui_HealthMeasureBtn, 36);
    lv_obj_set_x(ui_HealthMeasureBtn, -1);
    lv_obj_set_y(ui_HealthMeasureBtn, 36);
    lv_obj_set_align(ui_HealthMeasureBtn, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_HealthMeasureBtn, LV_STATE_PRESSED);       /// States
    lv_obj_add_flag(ui_HealthMeasureBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HealthMeasureBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HealthMeasureBtn, 21, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HealthMeasureBtn, lv_color_hex(0xEB5E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HealthMeasureBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_HealthMeasureBtn, lv_color_hex(0x7C3AED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_HealthMeasureBtn, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_HealthMeasureBtn, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_HealthMeasureBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_HealthMeasureBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_HealthMeasureBtn, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_HealthMeasureBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_HealthMeasureBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_HealthMeasureBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_HealthMeasureBtn, 18, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_HealthMeasureBtn, lv_color_hex(0xD93654), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_HealthMeasureBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_HealthMeasureBtn, lv_color_hex(0xFF4567), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_HealthMeasureBtn, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_MeasureBtnLabel = lv_label_create(ui_HealthMeasureBtn);
    lv_obj_set_width(ui_MeasureBtnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeasureBtnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MeasureBtnLabel, -21);
    lv_obj_set_y(ui_MeasureBtnLabel, 2);
    lv_obj_set_align(ui_MeasureBtnLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MeasureBtnLabel, "Start Measuring");
    lv_obj_set_style_text_color(ui_MeasureBtnLabel, lv_color_hex(0xF8EDED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MeasureBtnLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MeasureBtnLabel, &ui_font_Smil16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MeasureIconPanel = lv_obj_create(ui_HealthMeasureBtn);
    lv_obj_set_width(ui_MeasureIconPanel, 36);
    lv_obj_set_height(ui_MeasureIconPanel, 31);
    lv_obj_set_x(ui_MeasureIconPanel, 110);
    lv_obj_set_y(ui_MeasureIconPanel, -1);
    lv_obj_set_align(ui_MeasureIconPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MeasureIconPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MeasureIconPanel, lv_color_hex(0x5D8EF4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MeasureIconPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_MeasureIconPanel, &ui_img_1349814123, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MeasureIconPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_MeasureIconPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_MeasureIconPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_MeasureIconPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_MeasureIconPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HealthMeasureBtn, ui_event_HealthMeasureBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenHealth, ui_event_ScreenHealth, LV_EVENT_ALL, NULL);

}

void ui_ScreenHealth_screen_destroy(void)
{
    if(ui_ScreenHealth) lv_obj_del(ui_ScreenHealth);

    // NULL screen variables
    ui_ScreenHealth = NULL;
    ui_Image22 = NULL;
    ui_HealthTopCard = NULL;
    ui_HeartInfoPanel = NULL;
    ui_Image23 = NULL;
    ui_HeartValueLabel = NULL;
    ui_Label20 = NULL;
    ui_HeartStateLabel = NULL;
    ui_HeartRangeLabel = NULL;
    ui_HeartImage = NULL;
    ui_bpmzhi = NULL;
    ui_HeartSpinner = NULL;
    ui_BloodOxygenPanel = NULL;
    ui_bleed1 = NULL;
    ui_blood_fill = NULL;
    ui_bleed2 = NULL;
    ui_HeartChartPanel = NULL;
    ui_HeartChart = NULL;
    ui_shijain1 = NULL;
    ui_shujian2 = NULL;
    ui_shijian3 = NULL;
    ui_shijiansi = NULL;
    ui_zong3 = NULL;
    ui_shijian5 = NULL;
    ui_zong2 = NULL;
    ui_zong1 = NULL;
    ui_zong0 = NULL;
    ui_Label28 = NULL;
    ui_Label29 = NULL;
    ui_MAXnumLabel = NULL;
    ui_MINNUMLabel = NULL;
    ui_HealthMeasureBtn = NULL;
    ui_MeasureBtnLabel = NULL;
    ui_MeasureIconPanel = NULL;

}
