// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: smartwatch

#include "../ui.h"

lv_obj_t * ui_ScreenCall = NULL;
lv_obj_t * ui_ImgCallBg = NULL;
lv_obj_t * ui_TopMask = NULL;
lv_obj_t * ui_LabelPageTitle = NULL;
lv_obj_t * ui_BottomInfoCard = NULL;
lv_obj_t * ui_LabelCallerName = NULL;
lv_obj_t * ui_LabelCallState = NULL;
lv_obj_t * ui_LabelCallSub = NULL;
lv_obj_t * ui_BtnReject = NULL;
lv_obj_t * ui_LabelReject = NULL;
lv_obj_t * ui_BtnAccept = NULL;
lv_obj_t * ui_LabelAccept = NULL;
// event funtions
void ui_event_ScreenCall(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenWeather, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenWeather_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenSport, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScreenSport_screen_init);
    }
}

// build funtions

void ui_ScreenCall_screen_init(void)
{
    ui_ScreenCall = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenCall, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenCall, lv_color_hex(0x050C14), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenCall, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgCallBg = lv_img_create(ui_ScreenCall);
    lv_img_set_src(ui_ImgCallBg, &ui_img_call_png);
    lv_obj_set_width(ui_ImgCallBg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgCallBg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgCallBg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgCallBg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgCallBg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopMask = lv_obj_create(ui_ScreenCall);
    lv_obj_set_width(ui_TopMask, 313);
    lv_obj_set_height(ui_TopMask, 18);
    lv_obj_set_x(ui_TopMask, 0);
    lv_obj_set_y(ui_TopMask, -111);
    lv_obj_set_align(ui_TopMask, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TopMask, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TopMask, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TopMask, lv_color_hex(0x050C14), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopMask, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TopMask, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_TopMask, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_TopMask, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TopMask, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TopMask, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPageTitle = lv_label_create(ui_TopMask);
    lv_obj_set_width(ui_LabelPageTitle, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_LabelPageTitle, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_LabelPageTitle, -5);
    lv_obj_set_y(ui_LabelPageTitle, 1);
    lv_obj_set_align(ui_LabelPageTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPageTitle, "CALL");
    lv_obj_set_style_text_color(ui_LabelPageTitle, lv_color_hex(0xF5F7FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPageTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomInfoCard = lv_obj_create(ui_ScreenCall);
    lv_obj_set_width(ui_BottomInfoCard, 310);
    lv_obj_set_height(ui_BottomInfoCard, 84);
    lv_obj_set_x(ui_BottomInfoCard, -1);
    lv_obj_set_y(ui_BottomInfoCard, 78);
    lv_obj_set_align(ui_BottomInfoCard, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BottomInfoCard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BottomInfoCard, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BottomInfoCard, lv_color_hex(0x071521), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomInfoCard, 185, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BottomInfoCard, lv_color_hex(0x164A63), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BottomInfoCard, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BottomInfoCard, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BottomInfoCard, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BottomInfoCard, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BottomInfoCard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BottomInfoCard, 35, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCallerName = lv_label_create(ui_BottomInfoCard);
    lv_obj_set_width(ui_LabelCallerName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCallerName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCallerName, -80);
    lv_obj_set_y(ui_LabelCallerName, -25);
    lv_obj_set_align(ui_LabelCallerName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCallerName, "SAMANTHA");
    lv_obj_set_style_text_color(ui_LabelCallerName, lv_color_hex(0xF5F7FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCallerName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCallerName, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCallState = lv_label_create(ui_BottomInfoCard);
    lv_obj_set_width(ui_LabelCallState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCallState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCallState, -79);
    lv_obj_set_y(ui_LabelCallState, -3);
    lv_obj_set_align(ui_LabelCallState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCallState, "Incoming call");
    lv_obj_set_style_text_color(ui_LabelCallState, lv_color_hex(0x39E58C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCallState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCallSub = lv_label_create(ui_BottomInfoCard);
    lv_obj_set_width(ui_LabelCallSub, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCallSub, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCallSub, -67);
    lv_obj_set_y(ui_LabelCallSub, 21);
    lv_obj_set_align(ui_LabelCallSub, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCallSub, "Mobile:   online");
    lv_obj_set_style_text_color(ui_LabelCallSub, lv_color_hex(0xA9B6C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCallSub, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCallSub, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnReject = lv_btn_create(ui_BottomInfoCard);
    lv_obj_set_width(ui_BtnReject, 55);
    lv_obj_set_height(ui_BtnReject, 58);
    lv_obj_set_x(ui_BtnReject, 45);
    lv_obj_set_y(ui_BtnReject, -1);
    lv_obj_set_align(ui_BtnReject, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnReject, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnReject, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnReject, 21, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnReject, lv_color_hex(0xD93654), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnReject, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BtnReject, lv_color_hex(0xE23299), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BtnReject, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnReject, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BtnReject, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BtnReject, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnReject, lv_color_hex(0xFF4567), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnReject, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnReject, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnReject, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelReject = lv_label_create(ui_BtnReject);
    lv_obj_set_width(ui_LabelReject, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelReject, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelReject, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelReject, "End");
    lv_obj_set_style_text_font(ui_LabelReject, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnAccept = lv_btn_create(ui_BottomInfoCard);
    lv_obj_set_width(ui_BtnAccept, 55);
    lv_obj_set_height(ui_BtnAccept, 58);
    lv_obj_set_x(ui_BtnAccept, 110);
    lv_obj_set_y(ui_BtnAccept, 0);
    lv_obj_set_align(ui_BtnAccept, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnAccept, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnAccept, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnAccept, 21, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnAccept, lv_color_hex(0x1FA85B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnAccept, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BtnAccept, lv_color_hex(0x39E58C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BtnAccept, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnAccept, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BtnAccept, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BtnAccept, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnAccept, lv_color_hex(0x39E58C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnAccept, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnAccept, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnAccept, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAccept = lv_label_create(ui_BtnAccept);
    lv_obj_set_width(ui_LabelAccept, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAccept, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelAccept, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAccept, "PICK");
    lv_obj_set_style_text_font(ui_LabelAccept, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenCall, ui_event_ScreenCall, LV_EVENT_ALL, NULL);

}

void ui_ScreenCall_screen_destroy(void)
{
    if(ui_ScreenCall) lv_obj_del(ui_ScreenCall);

    // NULL screen variables
    ui_ScreenCall = NULL;
    ui_ImgCallBg = NULL;
    ui_TopMask = NULL;
    ui_LabelPageTitle = NULL;
    ui_BottomInfoCard = NULL;
    ui_LabelCallerName = NULL;
    ui_LabelCallState = NULL;
    ui_LabelCallSub = NULL;
    ui_BtnReject = NULL;
    ui_LabelReject = NULL;
    ui_BtnAccept = NULL;
    ui_LabelAccept = NULL;

}
