// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: smartwatch

#ifndef UI_SCREENSPORT_H
#define UI_SCREENSPORT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenSport
extern void ui_ScreenSport_screen_init(void);
extern void ui_ScreenSport_screen_destroy(void);
extern void ui_event_ScreenSport(lv_event_t * e);
extern lv_obj_t * ui_ScreenSport;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Image31;
extern lv_obj_t * ui_SportMainCard;
extern lv_obj_t * ui_SportArc;
extern lv_obj_t * ui_Image32;
extern lv_obj_t * ui_BtnPrev;
extern lv_obj_t * ui_BtnNext;
extern lv_obj_t * ui_LabelSportMode;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_ImgHeartSmall;
extern lv_obj_t * ui_LabelSportHeart;
extern lv_obj_t * ui_CardCalories;
extern lv_obj_t * ui_ImgCalories;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_CardDuration;
extern lv_obj_t * ui_ImgCalories1;
extern lv_obj_t * ui_Duration;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_min1;
extern lv_obj_t * ui_CardDistance;
extern lv_obj_t * ui_ImgCalories2;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern void ui_event_BtnSportStart(lv_event_t * e);
extern lv_obj_t * ui_BtnSportStart;
extern lv_obj_t * ui_LabelSportStart;
extern lv_obj_t * ui_PlayCircle;
extern lv_obj_t * ui_Image37;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

