// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: smartwatch

#ifndef UI_SCREENCALL_H
#define UI_SCREENCALL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenCall
extern void ui_ScreenCall_screen_init(void);
extern void ui_ScreenCall_screen_destroy(void);
extern void ui_event_ScreenCall(lv_event_t * e);
extern lv_obj_t * ui_ScreenCall;
extern lv_obj_t * ui_ImgCallBg;
extern lv_obj_t * ui_TopMask;
extern lv_obj_t * ui_LabelPageTitle;
extern lv_obj_t * ui_BottomInfoCard;
extern lv_obj_t * ui_LabelCallerName;
extern lv_obj_t * ui_LabelCallState;
extern lv_obj_t * ui_LabelCallSub;
extern lv_obj_t * ui_BtnReject;
extern lv_obj_t * ui_LabelReject;
extern lv_obj_t * ui_BtnAccept;
extern lv_obj_t * ui_LabelAccept;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

