// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: smartwatch

#include "../ui.h"

lv_obj_t * ui_ScreenWeather = NULL;
lv_obj_t * ui_WeatherMainCard = NULL;
lv_obj_t * ui_LabelLocation = NULL;
lv_obj_t * ui_Image38 = NULL;
lv_obj_t * ui_LabelDate = NULL;
lv_obj_t * ui_LabelTemp = NULL;
lv_obj_t * ui_LabelCondition = NULL;
lv_obj_t * ui_LabelHighLow = NULL;
lv_obj_t * ui_ImgWeatherMain = NULL;
lv_obj_t * ui_ForecastCard = NULL;
lv_obj_t * ui_ForecastPage1 = NULL;
lv_obj_t * ui_Label53 = NULL;
lv_obj_t * ui_Image43 = NULL;
lv_obj_t * ui_ForecastPage2 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_ForecastPage3 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_ForecastPage4 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_ForecastPage5 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_ForecastPage6 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_ForecastPage7 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_Image10 = NULL;
// event funtions
void ui_event_ScreenWeather(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        weathermainenter_Animation(ui_WeatherMainCard, 0);
        forecastcardenter_Animation(ui_ForecastCard, 0);
        weathericonfloat_Animation(ui_ImgWeatherMain, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenHealth, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenHealth_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenCall, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScreenCall_screen_init);
    }
}

// build funtions

void ui_ScreenWeather_screen_init(void)
{
    ui_ScreenWeather = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenWeather, lv_color_hex(0x050C14), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenWeather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherMainCard = lv_obj_create(ui_ScreenWeather);
    lv_obj_set_width(ui_WeatherMainCard, 304);
    lv_obj_set_height(ui_WeatherMainCard, 128);
    lv_obj_set_x(ui_WeatherMainCard, -1);
    lv_obj_set_y(ui_WeatherMainCard, -54);
    lv_obj_set_align(ui_WeatherMainCard, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WeatherMainCard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WeatherMainCard, lv_color_hex(0x071521), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WeatherMainCard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WeatherMainCard, lv_color_hex(0x16D9E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WeatherMainCard, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WeatherMainCard, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLocation = lv_label_create(ui_WeatherMainCard);
    lv_obj_set_width(ui_LabelLocation, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLocation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLocation, -77);
    lv_obj_set_y(ui_LabelLocation, -47);
    lv_obj_set_align(ui_LabelLocation, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLocation, "New York");
    lv_obj_set_style_text_color(ui_LabelLocation, lv_color_hex(0xF5F7FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLocation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLocation, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image38 = lv_img_create(ui_WeatherMainCard);
    lv_img_set_src(ui_Image38, &ui_img_482543466);
    lv_obj_set_width(ui_Image38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image38, -127);
    lv_obj_set_y(ui_Image38, -45);
    lv_obj_set_align(ui_Image38, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image38, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image38, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelDate = lv_label_create(ui_WeatherMainCard);
    lv_obj_set_width(ui_LabelDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDate, -75);
    lv_obj_set_y(ui_LabelDate, -27);
    lv_obj_set_align(ui_LabelDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDate, "03.01 Monday");
    lv_obj_set_style_text_color(ui_LabelDate, lv_color_hex(0xA9B6C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDate, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTemp = lv_label_create(ui_WeatherMainCard);
    lv_obj_set_width(ui_LabelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemp, -78);
    lv_obj_set_y(ui_LabelTemp, -1);
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemp, "25°");
    lv_obj_set_style_text_color(ui_LabelTemp, lv_color_hex(0xF5F7FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTemp, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCondition = lv_label_create(ui_WeatherMainCard);
    lv_obj_set_width(ui_LabelCondition, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCondition, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCondition, -84);
    lv_obj_set_y(ui_LabelCondition, 25);
    lv_obj_set_align(ui_LabelCondition, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCondition, "Partly Cloudy");
    lv_obj_set_style_text_color(ui_LabelCondition, lv_color_hex(0x16D9E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCondition, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCondition, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHighLow = lv_label_create(ui_WeatherMainCard);
    lv_obj_set_width(ui_LabelHighLow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHighLow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHighLow, -87);
    lv_obj_set_y(ui_LabelHighLow, 48);
    lv_obj_set_align(ui_LabelHighLow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHighLow, "#FF4567 H:28°#  #248CFF L:18°#");
    lv_label_set_recolor(ui_LabelHighLow, "true");
    lv_obj_set_style_text_color(ui_LabelHighLow, lv_color_hex(0xA9B6C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHighLow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgWeatherMain = lv_img_create(ui_WeatherMainCard);
    lv_img_set_src(ui_ImgWeatherMain, &ui_img_1772208564);
    lv_obj_set_width(ui_ImgWeatherMain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgWeatherMain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgWeatherMain, 61);
    lv_obj_set_y(ui_ImgWeatherMain, -5);
    lv_obj_set_align(ui_ImgWeatherMain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgWeatherMain, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgWeatherMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ForecastCard = lv_obj_create(ui_ScreenWeather);
    lv_obj_set_width(ui_ForecastCard, 305);
    lv_obj_set_height(ui_ForecastCard, 73);
    lv_obj_set_x(ui_ForecastCard, 1);
    lv_obj_set_y(ui_ForecastCard, 50);
    lv_obj_set_align(ui_ForecastCard, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ForecastCard, LV_FLEX_FLOW_COLUMN_WRAP_REVERSE);
    lv_obj_set_flex_align(ui_ForecastCard, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ForecastCard, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_ForecastCard, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_ForecastCard, LV_DIR_HOR);
    lv_obj_set_scroll_snap_x(ui_ForecastCard, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_radius(ui_ForecastCard, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ForecastCard, lv_color_hex(0x081827), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ForecastCard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ForecastCard, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ForecastCard, lv_color_hex(0x164A63), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ForecastCard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ForecastCard, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ForecastPage1 = lv_obj_create(ui_ForecastCard);
    lv_obj_set_width(ui_ForecastPage1, 43);
    lv_obj_set_height(ui_ForecastPage1, 63);
    lv_obj_set_x(ui_ForecastPage1, -119);
    lv_obj_set_y(ui_ForecastPage1, -2);
    lv_obj_set_align(ui_ForecastPage1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ForecastPage1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ForecastPage1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ForecastPage1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ForecastPage1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ForecastPage1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ForecastPage1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ForecastPage1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ForecastPage1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ForecastPage1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ForecastPage1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ForecastPage1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ForecastPage1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ForecastPage1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label53 = lv_label_create(ui_ForecastPage1);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label53, "18:00\n\n\n18°");
    lv_obj_set_style_text_color(ui_Label53, lv_color_hex(0xF5F7FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label53, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label53, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label53, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label53, lv_color_hex(0x164A63), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label53, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label53, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image43 = lv_img_create(ui_ForecastPage1);
    lv_img_set_src(ui_Image43, &ui_img_942679780);
    lv_obj_set_width(ui_Image43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image43, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image43, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image43, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ForecastPage2 = lv_obj_create(ui_ForecastCard);
    lv_obj_set_width(ui_ForecastPage2, 43);
    lv_obj_set_height(ui_ForecastPage2, 63);
    lv_obj_set_x(ui_ForecastPage2, -70);
    lv_obj_set_y(ui_ForecastPage2, 0);
    lv_obj_set_align(ui_ForecastPage2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ForecastPage2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ForecastPage2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ForecastPage2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ForecastPage2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ForecastPage2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ForecastPage2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ForecastPage2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ForecastPage2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ForecastPage2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ForecastPage2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ForecastPage2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ForecastPage2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ForecastPage2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_ForecastPage2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "16:00\n\n\n18°");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xF5F7FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label4, lv_color_hex(0x164A63), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_ForecastPage2);
    lv_img_set_src(ui_Image5, &ui_img_2087202441);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ForecastPage3 = lv_obj_create(ui_ForecastCard);
    lv_obj_set_width(ui_ForecastPage3, 43);
    lv_obj_set_height(ui_ForecastPage3, 63);
    lv_obj_set_x(ui_ForecastPage3, -16);
    lv_obj_set_y(ui_ForecastPage3, 1);
    lv_obj_set_align(ui_ForecastPage3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ForecastPage3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ForecastPage3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ForecastPage3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ForecastPage3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ForecastPage3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ForecastPage3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ForecastPage3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ForecastPage3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ForecastPage3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ForecastPage3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ForecastPage3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ForecastPage3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ForecastPage3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_ForecastPage3);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "14:00\n\n\n20°");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xF5F7FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label5, lv_color_hex(0x164A63), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_ForecastPage3);
    lv_img_set_src(ui_Image6, &ui_img_1607374796);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ForecastPage4 = lv_obj_create(ui_ForecastCard);
    lv_obj_set_width(ui_ForecastPage4, 43);
    lv_obj_set_height(ui_ForecastPage4, 63);
    lv_obj_set_x(ui_ForecastPage4, 37);
    lv_obj_set_y(ui_ForecastPage4, -1);
    lv_obj_set_align(ui_ForecastPage4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ForecastPage4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ForecastPage4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ForecastPage4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ForecastPage4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ForecastPage4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ForecastPage4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ForecastPage4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ForecastPage4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ForecastPage4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ForecastPage4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ForecastPage4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ForecastPage4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ForecastPage4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_ForecastPage4);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "12:00\n\n\n18°");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xF5F7FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label7, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label7, lv_color_hex(0x164A63), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_ForecastPage4);
    lv_img_set_src(ui_Image7, &ui_img_1369692798);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ForecastPage5 = lv_obj_create(ui_ForecastCard);
    lv_obj_set_width(ui_ForecastPage5, 43);
    lv_obj_set_height(ui_ForecastPage5, 63);
    lv_obj_set_x(ui_ForecastPage5, 94);
    lv_obj_set_y(ui_ForecastPage5, -2);
    lv_obj_set_align(ui_ForecastPage5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ForecastPage5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ForecastPage5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ForecastPage5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ForecastPage5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ForecastPage5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ForecastPage5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ForecastPage5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ForecastPage5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ForecastPage5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ForecastPage5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ForecastPage5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ForecastPage5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ForecastPage5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_ForecastPage5);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "09:00\n\n\n24°");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xF5F7FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label11, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label11, lv_color_hex(0x164A63), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_ForecastPage5);
    lv_img_set_src(ui_Image8, &ui_img_1225357782);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ForecastPage6 = lv_obj_create(ui_ForecastCard);
    lv_obj_set_width(ui_ForecastPage6, 43);
    lv_obj_set_height(ui_ForecastPage6, 63);
    lv_obj_set_x(ui_ForecastPage6, 140);
    lv_obj_set_y(ui_ForecastPage6, 0);
    lv_obj_set_align(ui_ForecastPage6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ForecastPage6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ForecastPage6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ForecastPage6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ForecastPage6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ForecastPage6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ForecastPage6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ForecastPage6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ForecastPage6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ForecastPage6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ForecastPage6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ForecastPage6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ForecastPage6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ForecastPage6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_ForecastPage6);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "06:00\n\n\n18°");
    lv_label_set_recolor(ui_Label19, "true");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xF5F7FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label19, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label19, lv_color_hex(0x164A63), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label19, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image9 = lv_img_create(ui_ForecastPage6);
    lv_img_set_src(ui_Image9, &ui_img_942679780);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ForecastPage7 = lv_obj_create(ui_ForecastCard);
    lv_obj_set_width(ui_ForecastPage7, 43);
    lv_obj_set_height(ui_ForecastPage7, 63);
    lv_obj_set_x(ui_ForecastPage7, 521);
    lv_obj_set_y(ui_ForecastPage7, 12);
    lv_obj_set_align(ui_ForecastPage7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ForecastPage7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ForecastPage7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ForecastPage7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ForecastPage7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ForecastPage7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ForecastPage7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ForecastPage7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ForecastPage7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ForecastPage7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ForecastPage7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ForecastPage7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ForecastPage7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ForecastPage7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_ForecastPage7);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "18:00\n\n\n18°");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0xF5F7FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label21, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label21, lv_color_hex(0x164A63), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label21, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_img_create(ui_ForecastPage7);
    lv_img_set_src(ui_Image10, &ui_img_1840017345);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ScreenWeather, ui_event_ScreenWeather, LV_EVENT_ALL, NULL);

}

void ui_ScreenWeather_screen_destroy(void)
{
    if(ui_ScreenWeather) lv_obj_del(ui_ScreenWeather);

    // NULL screen variables
    ui_ScreenWeather = NULL;
    ui_WeatherMainCard = NULL;
    ui_LabelLocation = NULL;
    ui_Image38 = NULL;
    ui_LabelDate = NULL;
    ui_LabelTemp = NULL;
    ui_LabelCondition = NULL;
    ui_LabelHighLow = NULL;
    ui_ImgWeatherMain = NULL;
    ui_ForecastCard = NULL;
    ui_ForecastPage1 = NULL;
    ui_Label53 = NULL;
    ui_Image43 = NULL;
    ui_ForecastPage2 = NULL;
    ui_Label4 = NULL;
    ui_Image5 = NULL;
    ui_ForecastPage3 = NULL;
    ui_Label5 = NULL;
    ui_Image6 = NULL;
    ui_ForecastPage4 = NULL;
    ui_Label7 = NULL;
    ui_Image7 = NULL;
    ui_ForecastPage5 = NULL;
    ui_Label11 = NULL;
    ui_Image8 = NULL;
    ui_ForecastPage6 = NULL;
    ui_Label19 = NULL;
    ui_Image9 = NULL;
    ui_ForecastPage7 = NULL;
    ui_Label21 = NULL;
    ui_Image10 = NULL;

}
