// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: smartwatch

#include "../ui.h"

lv_obj_t * ui_ScreenHome = NULL;
lv_obj_t * ui_ImgHomeBackground = NULL;
lv_obj_t * ui_LabelDate1 = NULL;
lv_obj_t * ui_HomeTimeLabel = NULL;
lv_obj_t * ui_dots = NULL;
lv_obj_t * ui_HomeDateLabel = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_HomeWeatherTempLabel = NULL;
lv_obj_t * ui_HomeWeatherStateLabel = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_HomeBatteryLabel = NULL;
lv_obj_t * ui_AnalogClock = NULL;
lv_obj_t * ui_HomeSecondHand = NULL;
lv_obj_t * ui_HomeMinuteHand = NULL;
lv_obj_t * ui_HomeHourHand = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_HomeTempLabel = NULL;
lv_obj_t * ui_Label1temp = NULL;
lv_obj_t * ui_HomeHumidityLabel = NULL;
lv_obj_t * ui_Label1hum = NULL;
lv_obj_t * ui_HomeStepLabel = NULL;
lv_obj_t * ui_Label1step = NULL;
lv_obj_t * ui_BottomNav = NULL;
lv_obj_t * ui_BtnNavCall = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_BtnNavSport = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_BtnNavHealth = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_BtnNavWeather = NULL;
lv_obj_t * ui_Label3 = NULL;
// event funtions
void ui_event_ScreenHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenHealth, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScreenHealth_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenSport, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenSport_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        homegroupfade_Animation(ui_LabelDate1, 0);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        homenaventer_Animation(ui_BottomNav, 0);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        home_screen_loaded_event(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        home_screen_unloaded_event(e);
    }
}

void ui_event_BtnNavCall(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenCall, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenCall_screen_init);
    }
}

void ui_event_BtnNavSport(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSport, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenSport_screen_init);
    }
}

void ui_event_BtnNavHealth(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHealth, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenHealth_screen_init);
    }
}

void ui_event_BtnNavWeather(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenWeather, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenWeather_screen_init);
    }
}

// build funtions

void ui_ScreenHome_screen_init(void)
{
    ui_ScreenHome = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ScreenHome, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScreenHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgHomeBackground = lv_img_create(ui_ScreenHome);
    lv_img_set_src(ui_ImgHomeBackground, &ui_img_bg4_png);
    lv_obj_set_width(ui_ImgHomeBackground, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgHomeBackground, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgHomeBackground, -3);
    lv_obj_set_y(ui_ImgHomeBackground, 0);
    lv_obj_set_align(ui_ImgHomeBackground, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgHomeBackground, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgHomeBackground, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgHomeBackground, 260);

    ui_LabelDate1 = lv_obj_create(ui_ScreenHome);
    lv_obj_set_width(ui_LabelDate1, 184);
    lv_obj_set_height(ui_LabelDate1, 83);
    lv_obj_set_x(ui_LabelDate1, -46);
    lv_obj_set_y(ui_LabelDate1, -46);
    lv_obj_set_align(ui_LabelDate1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LabelDate1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LabelDate1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelDate1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelDate1, lv_color_hex(0x1B71E7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelDate1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeTimeLabel = lv_label_create(ui_LabelDate1);
    lv_obj_set_width(ui_HomeTimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeTimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeTimeLabel, -16);
    lv_obj_set_y(ui_HomeTimeLabel, -25);
    lv_obj_set_align(ui_HomeTimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeTimeLabel, "10 08");
    lv_obj_set_style_text_color(ui_HomeTimeLabel, lv_color_hex(0xF5ECED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeTimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeTimeLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dots = lv_label_create(ui_LabelDate1);
    lv_obj_set_width(ui_dots, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dots, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dots, -20);
    lv_obj_set_y(ui_dots, -25);
    lv_obj_set_align(ui_dots, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dots, ":");
    lv_obj_set_style_text_color(ui_dots, lv_color_hex(0xF5EFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dots, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeDateLabel = lv_label_create(ui_LabelDate1);
    lv_obj_set_width(ui_HomeDateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeDateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeDateLabel, -12);
    lv_obj_set_y(ui_HomeDateLabel, 0);
    lv_obj_set_align(ui_HomeDateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeDateLabel, "May 20 2026 Mon");
    lv_obj_set_style_text_color(ui_HomeDateLabel, lv_color_hex(0xF9F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeDateLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_LabelDate1);
    lv_img_set_src(ui_Image2, &ui_img_weather_sun_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -67);
    lv_obj_set_y(ui_Image2, 24);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 222);

    ui_HomeWeatherTempLabel = lv_label_create(ui_LabelDate1);
    lv_obj_set_width(ui_HomeWeatherTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeWeatherTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeWeatherTempLabel, -33);
    lv_obj_set_y(ui_HomeWeatherTempLabel, 25);
    lv_obj_set_align(ui_HomeWeatherTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeWeatherTempLabel, "25°");
    lv_obj_set_style_text_color(ui_HomeWeatherTempLabel, lv_color_hex(0xF4EFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeWeatherTempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeWeatherStateLabel = lv_label_create(ui_LabelDate1);
    lv_obj_set_width(ui_HomeWeatherStateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeWeatherStateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeWeatherStateLabel, 32);
    lv_obj_set_y(ui_HomeWeatherStateLabel, 25);
    lv_obj_set_align(ui_HomeWeatherStateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeWeatherStateLabel, "Partly Cloudy");
    lv_obj_set_style_text_color(ui_HomeWeatherStateLabel, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeWeatherStateLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_ScreenHome);
    lv_obj_set_width(ui_Panel4, 73);
    lv_obj_set_height(ui_Panel4, 19);
    lv_obj_set_x(ui_Panel4, 106);
    lv_obj_set_y(ui_Panel4, -103);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel4, LV_FLEX_FLOW_COLUMN_WRAP_REVERSE);
    lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_Panel4);
    lv_img_set_src(ui_Image3, &ui_img_flash_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 200);

    ui_HomeBatteryLabel = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_HomeBatteryLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeBatteryLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HomeBatteryLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeBatteryLabel, "90%");
    lv_obj_set_style_text_color(ui_HomeBatteryLabel, lv_color_hex(0xF8F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeBatteryLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AnalogClock = lv_obj_create(ui_ScreenHome);
    lv_obj_set_width(ui_AnalogClock, 72);
    lv_obj_set_height(ui_AnalogClock, 77);
    lv_obj_set_x(ui_AnalogClock, 87);
    lv_obj_set_y(ui_AnalogClock, -44);
    lv_obj_set_align(ui_AnalogClock, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AnalogClock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AnalogClock, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AnalogClock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AnalogClock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_AnalogClock, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AnalogClock, lv_color_hex(0x0E95E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AnalogClock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeSecondHand = lv_img_create(ui_AnalogClock);
    lv_img_set_src(ui_HomeSecondHand, &ui_img_clockwise_sec_png);
    lv_obj_set_width(ui_HomeSecondHand, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeSecondHand, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeSecondHand, 1);
    lv_obj_set_y(ui_HomeSecondHand, -60);
    lv_obj_set_align(ui_HomeSecondHand, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeSecondHand, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeSecondHand, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_HomeSecondHand, 15, 155);
    lv_img_set_angle(ui_HomeSecondHand, 12000);
    lv_img_set_zoom(ui_HomeSecondHand, 50);

    ui_HomeMinuteHand = lv_img_create(ui_AnalogClock);
    lv_img_set_src(ui_HomeMinuteHand, &ui_img_clockwise_min_png);
    lv_obj_set_width(ui_HomeMinuteHand, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeMinuteHand, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeMinuteHand, 0);
    lv_obj_set_y(ui_HomeMinuteHand, -67);
    lv_obj_set_align(ui_HomeMinuteHand, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeMinuteHand, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeMinuteHand, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_HomeMinuteHand, 9, 145);
    lv_img_set_angle(ui_HomeMinuteHand, 9);
    lv_img_set_zoom(ui_HomeMinuteHand, 60);

    ui_HomeHourHand = lv_img_create(ui_AnalogClock);
    lv_img_set_src(ui_HomeHourHand, &ui_img_clockwise_hour_png);
    lv_obj_set_width(ui_HomeHourHand, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeHourHand, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeHourHand, 0);
    lv_obj_set_y(ui_HomeHourHand, -35);
    lv_obj_set_align(ui_HomeHourHand, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeHourHand, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeHourHand, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_HomeHourHand, 9, 84);
    lv_img_set_zoom(ui_HomeHourHand, 70);

    ui_Image11 = lv_img_create(ui_ScreenHome);
    lv_img_set_src(ui_Image11, &ui_img_843332074);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image11, -121);
    lv_obj_set_y(ui_Image11, 27);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image11, 220);

    ui_Image12 = lv_img_create(ui_ScreenHome);
    lv_img_set_src(ui_Image12, &ui_img_545021016);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image12, -29);
    lv_obj_set_y(ui_Image12, 26);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image12, 200);

    ui_Image13 = lv_img_create(ui_ScreenHome);
    lv_img_set_src(ui_Image13, &ui_img_step_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image13, 70);
    lv_obj_set_y(ui_Image13, 25);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeTempLabel = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_HomeTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeTempLabel, -82);
    lv_obj_set_y(ui_HomeTempLabel, 33);
    lv_obj_set_align(ui_HomeTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeTempLabel, "50°");
    lv_obj_set_style_text_color(ui_HomeTempLabel, lv_color_hex(0x15AAEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeTempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeTempLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1temp = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_Label1temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1temp, -81);
    lv_obj_set_y(ui_Label1temp, 14);
    lv_obj_set_align(ui_Label1temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1temp, "temp");
    lv_obj_set_style_text_color(ui_Label1temp, lv_color_hex(0x0B73D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeHumidityLabel = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_HomeHumidityLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeHumidityLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeHumidityLabel, 13);
    lv_obj_set_y(ui_HomeHumidityLabel, 36);
    lv_obj_set_align(ui_HomeHumidityLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeHumidityLabel, "60%");
    lv_obj_set_style_text_color(ui_HomeHumidityLabel, lv_color_hex(0x15AAEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeHumidityLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeHumidityLabel, &ui_font_Smil16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1hum = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_Label1hum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1hum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1hum, 14);
    lv_obj_set_y(ui_Label1hum, 16);
    lv_obj_set_align(ui_Label1hum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1hum, "Hum");
    lv_obj_set_style_text_color(ui_Label1hum, lv_color_hex(0x0B73D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1hum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeStepLabel = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_HomeStepLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeStepLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeStepLabel, 108);
    lv_obj_set_y(ui_HomeStepLabel, 36);
    lv_obj_set_align(ui_HomeStepLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeStepLabel, "7000");
    lv_obj_set_style_text_color(ui_HomeStepLabel, lv_color_hex(0x0B73D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeStepLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1step = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_Label1step, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1step, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1step, 109);
    lv_obj_set_y(ui_Label1step, 16);
    lv_obj_set_align(ui_Label1step, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1step, "Step");
    lv_obj_set_style_text_color(ui_Label1step, lv_color_hex(0x0B73D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1step, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNav = lv_obj_create(ui_ScreenHome);
    lv_obj_set_width(ui_BottomNav, 281);
    lv_obj_set_height(ui_BottomNav, 50);
    lv_obj_set_x(ui_BottomNav, -4);
    lv_obj_set_y(ui_BottomNav, 79);
    lv_obj_set_align(ui_BottomNav, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BottomNav, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BottomNav, lv_color_hex(0x071521), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomNav, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BottomNav, lv_color_hex(0x16D9E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BottomNav, lv_color_hex(0x16D9E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BottomNav, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNavCall = lv_btn_create(ui_BottomNav);
    lv_obj_set_width(ui_BtnNavCall, 33);
    lv_obj_set_height(ui_BtnNavCall, 29);
    lv_obj_set_x(ui_BtnNavCall, -104);
    lv_obj_set_y(ui_BtnNavCall, -8);
    lv_obj_set_align(ui_BtnNavCall, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnNavCall, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNavCall, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnNavCall, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnNavCall, lv_color_hex(0x071521), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNavCall, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnNavCall, &ui_img_1154559383, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnNavCall, lv_color_hex(0x16D9E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnNavCall, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnNavCall, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_BottomNav);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -102);
    lv_obj_set_y(ui_Label16, 16);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Call");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x16D9E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNavSport = lv_btn_create(ui_BottomNav);
    lv_obj_set_width(ui_BtnNavSport, 33);
    lv_obj_set_height(ui_BtnNavSport, 29);
    lv_obj_set_x(ui_BtnNavSport, -34);
    lv_obj_set_y(ui_BtnNavSport, -8);
    lv_obj_set_align(ui_BtnNavSport, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnNavSport, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNavSport, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnNavSport, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnNavSport, lv_color_hex(0x071521), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNavSport, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnNavSport, &ui_img_623432142, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnNavSport, lv_color_hex(0x16D9E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnNavSport, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnNavSport, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_BottomNav);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 105);
    lv_obj_set_y(ui_Label2, 15);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Weather");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x16D9E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNavHealth = lv_btn_create(ui_BottomNav);
    lv_obj_set_width(ui_BtnNavHealth, 33);
    lv_obj_set_height(ui_BtnNavHealth, 29);
    lv_obj_set_x(ui_BtnNavHealth, 32);
    lv_obj_set_y(ui_BtnNavHealth, -8);
    lv_obj_set_align(ui_BtnNavHealth, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnNavHealth, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNavHealth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnNavHealth, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnNavHealth, lv_color_hex(0x071521), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNavHealth, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnNavHealth, &ui_img_heart_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnNavHealth, lv_color_hex(0x16D9E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnNavHealth, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnNavHealth, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_BottomNav);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 32);
    lv_obj_set_y(ui_Label18, 16);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Health");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0x16D9E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNavWeather = lv_btn_create(ui_BottomNav);
    lv_obj_set_width(ui_BtnNavWeather, 33);
    lv_obj_set_height(ui_BtnNavWeather, 29);
    lv_obj_set_x(ui_BtnNavWeather, 102);
    lv_obj_set_y(ui_BtnNavWeather, -8);
    lv_obj_set_align(ui_BtnNavWeather, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnNavWeather, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNavWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnNavWeather, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnNavWeather, lv_color_hex(0x071521), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNavWeather, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnNavWeather, &ui_img_1684792934, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnNavWeather, lv_color_hex(0x16D9E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnNavWeather, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnNavWeather, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_BottomNav);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -33);
    lv_obj_set_y(ui_Label3, 15);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Sport");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x16D9E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnNavCall, ui_event_BtnNavCall, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNavSport, ui_event_BtnNavSport, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNavHealth, ui_event_BtnNavHealth, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNavWeather, ui_event_BtnNavWeather, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenHome, ui_event_ScreenHome, LV_EVENT_ALL, NULL);

}

void ui_ScreenHome_screen_destroy(void)
{
    if(ui_ScreenHome) lv_obj_del(ui_ScreenHome);

    // NULL screen variables
    ui_ScreenHome = NULL;
    ui_ImgHomeBackground = NULL;
    ui_LabelDate1 = NULL;
    ui_HomeTimeLabel = NULL;
    ui_dots = NULL;
    ui_HomeDateLabel = NULL;
    ui_Image2 = NULL;
    ui_HomeWeatherTempLabel = NULL;
    ui_HomeWeatherStateLabel = NULL;
    ui_Panel4 = NULL;
    ui_Image3 = NULL;
    ui_HomeBatteryLabel = NULL;
    ui_AnalogClock = NULL;
    ui_HomeSecondHand = NULL;
    ui_HomeMinuteHand = NULL;
    ui_HomeHourHand = NULL;
    ui_Image11 = NULL;
    ui_Image12 = NULL;
    ui_Image13 = NULL;
    ui_HomeTempLabel = NULL;
    ui_Label1temp = NULL;
    ui_HomeHumidityLabel = NULL;
    ui_Label1hum = NULL;
    ui_HomeStepLabel = NULL;
    ui_Label1step = NULL;
    ui_BottomNav = NULL;
    ui_BtnNavCall = NULL;
    ui_Label16 = NULL;
    ui_BtnNavSport = NULL;
    ui_Label2 = NULL;
    ui_BtnNavHealth = NULL;
    ui_Label18 = NULL;
    ui_BtnNavWeather = NULL;
    ui_Label3 = NULL;

}
