// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: smartwatch

#include "../ui.h"

lv_obj_t * ui_ScreenSport = NULL;
lv_obj_t * ui_Panel20 = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_Label33 = NULL;
lv_obj_t * ui_Image31 = NULL;
lv_obj_t * ui_SportMainCard = NULL;
lv_obj_t * ui_SportArc = NULL;
lv_obj_t * ui_Image32 = NULL;
lv_obj_t * ui_BtnPrev = NULL;
lv_obj_t * ui_BtnNext = NULL;
lv_obj_t * ui_LabelSportMode = NULL;
lv_obj_t * ui_Label37 = NULL;
lv_obj_t * ui_ImgHeartSmall = NULL;
lv_obj_t * ui_LabelSportHeart = NULL;
lv_obj_t * ui_CardCalories = NULL;
lv_obj_t * ui_ImgCalories = NULL;
lv_obj_t * ui_Label40 = NULL;
lv_obj_t * ui_Label41 = NULL;
lv_obj_t * ui_Label42 = NULL;
lv_obj_t * ui_CardDuration = NULL;
lv_obj_t * ui_ImgCalories1 = NULL;
lv_obj_t * ui_Duration = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_min1 = NULL;
lv_obj_t * ui_CardDistance = NULL;
lv_obj_t * ui_ImgCalories2 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_BtnSportStart = NULL;
lv_obj_t * ui_LabelSportStart = NULL;
lv_obj_t * ui_PlayCircle = NULL;
lv_obj_t * ui_Image37 = NULL;
// event funtions
void ui_event_ScreenSport(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        sportarcenter_Animation(ui_SportArc, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScreenHome_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenCall, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenCall_screen_init);
    }
}

void ui_event_BtnSportStart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_checked_set_text_value(ui_LabelSportStart, target, "STOP", "START");
    }
}

// build funtions

void ui_ScreenSport_screen_init(void)
{
    ui_ScreenSport = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSport, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenSport, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenSport, lv_color_hex(0x050C14), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenSport, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ScreenSport, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel20 = lv_obj_create(ui_ScreenSport);
    lv_obj_set_width(ui_Panel20, 312);
    lv_obj_set_height(ui_Panel20, 24);
    lv_obj_set_x(ui_Panel20, 0);
    lv_obj_set_y(ui_Panel20, -108);
    lv_obj_set_align(ui_Panel20, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel20, lv_color_hex(0x0F2033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_Panel20);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, -8);
    lv_obj_set_y(ui_Label32, -1);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "Sport");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0x16D9E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label32, &ui_font_Smil16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_Panel20);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, 143);
    lv_obj_set_y(ui_Label33, 1);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "80%");
    lv_obj_set_style_text_color(ui_Label33, lv_color_hex(0xF5F7FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label33, &ui_font_Smil16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image31 = lv_img_create(ui_Panel20);
    lv_img_set_src(ui_Image31, &ui_img_1197078990);
    lv_obj_set_width(ui_Image31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image31, 115);
    lv_obj_set_y(ui_Image31, 0);
    lv_obj_set_align(ui_Image31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image31, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image31, 900);
    lv_img_set_zoom(ui_Image31, 270);

    ui_SportMainCard = lv_obj_create(ui_ScreenSport);
    lv_obj_set_width(ui_SportMainCard, 304);
    lv_obj_set_height(ui_SportMainCard, 74);
    lv_obj_set_x(ui_SportMainCard, -2);
    lv_obj_set_y(ui_SportMainCard, -60);
    lv_obj_set_align(ui_SportMainCard, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SportMainCard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SportMainCard, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SportMainCard, lv_color_hex(0x071521), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SportMainCard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SportMainCard, lv_color_hex(0x164A63), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SportMainCard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SportArc = lv_arc_create(ui_SportMainCard);
    lv_obj_set_width(ui_SportArc, 75);
    lv_obj_set_height(ui_SportArc, 65);
    lv_obj_set_x(ui_SportArc, -59);
    lv_obj_set_y(ui_SportArc, -1);
    lv_obj_set_align(ui_SportArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_SportArc, 60);
    lv_arc_set_bg_angles(ui_SportArc, 135, 405);
    lv_obj_set_style_arc_color(ui_SportArc, lv_color_hex(0x16304A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SportArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SportArc, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_SportArc, lv_color_hex(0x248CFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SportArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SportArc, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SportArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SportArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Image32 = lv_img_create(ui_SportMainCard);
    lv_img_set_src(ui_Image32, &ui_img_616669363);
    lv_obj_set_width(ui_Image32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image32, -63);
    lv_obj_set_y(ui_Image32, -2);
    lv_obj_set_align(ui_Image32, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image32, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnPrev = lv_imgbtn_create(ui_SportMainCard);
    lv_imgbtn_set_src(ui_BtnPrev, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1657355558, NULL);
    lv_obj_set_width(ui_BtnPrev, 17);
    lv_obj_set_height(ui_BtnPrev, 14);
    lv_obj_set_x(ui_BtnPrev, -124);
    lv_obj_set_y(ui_BtnPrev, -1);
    lv_obj_set_align(ui_BtnPrev, LV_ALIGN_CENTER);

    ui_BtnNext = lv_imgbtn_create(ui_SportMainCard);
    lv_imgbtn_set_src(ui_BtnNext, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_375917039, NULL);
    lv_obj_set_width(ui_BtnNext, 15);
    lv_obj_set_height(ui_BtnNext, 18);
    lv_obj_set_x(ui_BtnNext, 127);
    lv_obj_set_y(ui_BtnNext, 3);
    lv_obj_set_align(ui_BtnNext, LV_ALIGN_CENTER);

    ui_LabelSportMode = lv_label_create(ui_SportMainCard);
    lv_obj_set_width(ui_LabelSportMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSportMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSportMode, 43);
    lv_obj_set_y(ui_LabelSportMode, -11);
    lv_obj_set_align(ui_LabelSportMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSportMode, "Outdoor Run\n");
    lv_obj_set_style_text_color(ui_LabelSportMode, lv_color_hex(0xF5F7FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSportMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSportMode, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_SportMainCard);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, 48);
    lv_obj_set_y(ui_Label37, 3);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "LabelSportStatus");
    lv_obj_set_style_text_color(ui_Label37, lv_color_hex(0x39E58C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label37, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgHeartSmall = lv_img_create(ui_SportMainCard);
    lv_img_set_src(ui_ImgHeartSmall, &ui_img_1389843189);
    lv_obj_set_width(ui_ImgHeartSmall, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgHeartSmall, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgHeartSmall, -2);
    lv_obj_set_y(ui_ImgHeartSmall, 24);
    lv_obj_set_align(ui_ImgHeartSmall, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgHeartSmall, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgHeartSmall, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgHeartSmall, 200);

    ui_LabelSportHeart = lv_label_create(ui_SportMainCard);
    lv_obj_set_width(ui_LabelSportHeart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSportHeart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSportHeart, 64);
    lv_obj_set_y(ui_LabelSportHeart, 30);
    lv_obj_set_align(ui_LabelSportHeart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSportHeart, "Heart 78 bpm\n");
    lv_obj_set_style_text_color(ui_LabelSportHeart, lv_color_hex(0xA9B6C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSportHeart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSportHeart, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CardCalories = lv_obj_create(ui_ScreenSport);
    lv_obj_set_width(ui_CardCalories, 96);
    lv_obj_set_height(ui_CardCalories, 63);
    lv_obj_set_x(ui_CardCalories, -103);
    lv_obj_set_y(ui_CardCalories, 15);
    lv_obj_set_align(ui_CardCalories, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CardCalories, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CardCalories, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CardCalories, lv_color_hex(0x081827), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CardCalories, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CardCalories, lv_color_hex(0x164A63), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CardCalories, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgCalories = lv_img_create(ui_CardCalories);
    lv_img_set_src(ui_ImgCalories, &ui_img_1814031685);
    lv_obj_set_width(ui_ImgCalories, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_ImgCalories, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_ImgCalories, -30);
    lv_obj_set_y(ui_ImgCalories, -16);
    lv_obj_set_align(ui_ImgCalories, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgCalories, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgCalories, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgCalories, 300);

    ui_Label40 = lv_label_create(ui_CardCalories);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, 13);
    lv_obj_set_y(ui_Label40, -17);
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "Calories");
    lv_obj_set_style_text_color(ui_Label40, lv_color_hex(0xCBC6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_CardCalories);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, 12);
    lv_obj_set_y(ui_Label41, 2);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "320");
    lv_obj_set_style_text_color(ui_Label41, lv_color_hex(0xFF9F43), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label41, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label42 = lv_label_create(ui_CardCalories);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label42, 29);
    lv_obj_set_y(ui_Label42, 21);
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "kcai");
    lv_obj_set_style_text_color(ui_Label42, lv_color_hex(0xCBC6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label42, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CardDuration = lv_obj_create(ui_ScreenSport);
    lv_obj_set_width(ui_CardDuration, 96);
    lv_obj_set_height(ui_CardDuration, 63);
    lv_obj_set_x(ui_CardDuration, -3);
    lv_obj_set_y(ui_CardDuration, 15);
    lv_obj_set_align(ui_CardDuration, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CardDuration, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CardDuration, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CardDuration, lv_color_hex(0x081827), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CardDuration, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CardDuration, lv_color_hex(0x164A63), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CardDuration, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgCalories1 = lv_img_create(ui_CardDuration);
    lv_img_set_src(ui_ImgCalories1, &ui_img_1611373906);
    lv_obj_set_width(ui_ImgCalories1, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_ImgCalories1, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_ImgCalories1, -32);
    lv_obj_set_y(ui_ImgCalories1, -17);
    lv_obj_set_align(ui_ImgCalories1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgCalories1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgCalories1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgCalories1, 300);

    ui_Duration = lv_label_create(ui_CardDuration);
    lv_obj_set_width(ui_Duration, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Duration, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Duration, 13);
    lv_obj_set_y(ui_Duration, -17);
    lv_obj_set_align(ui_Duration, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Duration, "Duratiuon");
    lv_obj_set_style_text_color(ui_Duration, lv_color_hex(0xCBC6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Duration, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Duration, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_CardDuration);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 12);
    lv_obj_set_y(ui_Label6, 2);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "30");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x1C9BDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_min1 = lv_label_create(ui_CardDuration);
    lv_obj_set_width(ui_min1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_min1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_min1, 29);
    lv_obj_set_y(ui_min1, 21);
    lv_obj_set_align(ui_min1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_min1, "min");
    lv_obj_set_style_text_color(ui_min1, lv_color_hex(0xCBC6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_min1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CardDistance = lv_obj_create(ui_ScreenSport);
    lv_obj_set_width(ui_CardDistance, 96);
    lv_obj_set_height(ui_CardDistance, 63);
    lv_obj_set_x(ui_CardDistance, 99);
    lv_obj_set_y(ui_CardDistance, 15);
    lv_obj_set_align(ui_CardDistance, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CardDistance, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CardDistance, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CardDistance, lv_color_hex(0x081827), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CardDistance, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CardDistance, lv_color_hex(0x164A63), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CardDistance, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgCalories2 = lv_img_create(ui_CardDistance);
    lv_img_set_src(ui_ImgCalories2, &ui_img_482543466);
    lv_obj_set_width(ui_ImgCalories2, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_ImgCalories2, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_ImgCalories2, -32);
    lv_obj_set_y(ui_ImgCalories2, -16);
    lv_obj_set_align(ui_ImgCalories2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgCalories2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgCalories2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgCalories2, 300);

    ui_Label8 = lv_label_create(ui_CardDistance);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 13);
    lv_obj_set_y(ui_Label8, -17);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Distance");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xCBC6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_CardDistance);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 12);
    lv_obj_set_y(ui_Label9, 2);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "200");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xE636CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_CardDistance);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 29);
    lv_obj_set_y(ui_Label10, 21);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "km");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xCBC6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSportStart = lv_btn_create(ui_ScreenSport);
    lv_obj_set_width(ui_BtnSportStart, 297);
    lv_obj_set_height(ui_BtnSportStart, 50);
    lv_obj_set_x(ui_BtnSportStart, -3);
    lv_obj_set_y(ui_BtnSportStart, 81);
    lv_obj_set_align(ui_BtnSportStart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSportStart, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSportStart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnSportStart, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnSportStart, lv_color_hex(0xE355A2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSportStart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BtnSportStart, lv_color_hex(0x7C3AED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BtnSportStart, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnSportStart, lv_color_hex(0x4F46E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnSportStart, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnSportStart, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnSportStart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_BtnSportStart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_BtnSportStart, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnSportStart, lv_color_hex(0xD93654), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BtnSportStart, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_BtnSportStart, lv_color_hex(0xFF4567), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_BtnSportStart, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_LabelSportStart = lv_label_create(ui_BtnSportStart);
    lv_obj_set_width(ui_LabelSportStart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSportStart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSportStart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSportStart, "START");
    lv_obj_set_style_text_color(ui_LabelSportStart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSportStart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSportStart, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlayCircle = lv_obj_create(ui_BtnSportStart);
    lv_obj_set_width(ui_PlayCircle, 45);
    lv_obj_set_height(ui_PlayCircle, 42);
    lv_obj_set_x(ui_PlayCircle, 105);
    lv_obj_set_y(ui_PlayCircle, 1);
    lv_obj_set_align(ui_PlayCircle, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PlayCircle, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PlayCircle, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PlayCircle, lv_color_hex(0x5B5FEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PlayCircle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PlayCircle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PlayCircle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PlayCircle, lv_color_hex(0xD93654), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_PlayCircle, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_PlayCircle, lv_color_hex(0xFF4567), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_PlayCircle, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image37 = lv_img_create(ui_PlayCircle);
    lv_img_set_src(ui_Image37, &ui_img_1349814123);
    lv_obj_set_width(ui_Image37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image37, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image37, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image37, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_BtnSportStart, ui_event_BtnSportStart, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenSport, ui_event_ScreenSport, LV_EVENT_ALL, NULL);

}

void ui_ScreenSport_screen_destroy(void)
{
    if(ui_ScreenSport) lv_obj_del(ui_ScreenSport);

    // NULL screen variables
    ui_ScreenSport = NULL;
    ui_Panel20 = NULL;
    ui_Label32 = NULL;
    ui_Label33 = NULL;
    ui_Image31 = NULL;
    ui_SportMainCard = NULL;
    ui_SportArc = NULL;
    ui_Image32 = NULL;
    ui_BtnPrev = NULL;
    ui_BtnNext = NULL;
    ui_LabelSportMode = NULL;
    ui_Label37 = NULL;
    ui_ImgHeartSmall = NULL;
    ui_LabelSportHeart = NULL;
    ui_CardCalories = NULL;
    ui_ImgCalories = NULL;
    ui_Label40 = NULL;
    ui_Label41 = NULL;
    ui_Label42 = NULL;
    ui_CardDuration = NULL;
    ui_ImgCalories1 = NULL;
    ui_Duration = NULL;
    ui_Label6 = NULL;
    ui_min1 = NULL;
    ui_CardDistance = NULL;
    ui_ImgCalories2 = NULL;
    ui_Label8 = NULL;
    ui_Label9 = NULL;
    ui_Label10 = NULL;
    ui_BtnSportStart = NULL;
    ui_LabelSportStart = NULL;
    ui_PlayCircle = NULL;
    ui_Image37 = NULL;

}
