// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: smartwatch

#ifndef UI_SCREENWEATHER_H
#define UI_SCREENWEATHER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenWeather
extern void ui_ScreenWeather_screen_init(void);
extern void ui_ScreenWeather_screen_destroy(void);
extern void ui_event_ScreenWeather(lv_event_t * e);
extern lv_obj_t * ui_ScreenWeather;
extern lv_obj_t * ui_WeatherMainCard;
extern lv_obj_t * ui_LabelLocation;
extern lv_obj_t * ui_Image38;
extern lv_obj_t * ui_LabelDate;
extern lv_obj_t * ui_LabelTemp;
extern lv_obj_t * ui_LabelCondition;
extern lv_obj_t * ui_LabelHighLow;
extern lv_obj_t * ui_ImgWeatherMain;
extern lv_obj_t * ui_ForecastCard;
extern lv_obj_t * ui_ForecastPage1;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_Image43;
extern lv_obj_t * ui_ForecastPage2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_ForecastPage3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_ForecastPage4;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_ForecastPage5;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_ForecastPage6;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_ForecastPage7;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Image10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

