// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: smartwatch

#ifndef UI_SCREENHEALTH_H
#define UI_SCREENHEALTH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenHealth
extern void ui_ScreenHealth_screen_init(void);
extern void ui_ScreenHealth_screen_destroy(void);
extern void ui_event_ScreenHealth(lv_event_t * e);
extern lv_obj_t * ui_ScreenHealth;
extern lv_obj_t * ui_Image22;
extern lv_obj_t * ui_HealthTopCard;
extern lv_obj_t * ui_HeartInfoPanel;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_HeartValueLabel;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_HeartStateLabel;
extern lv_obj_t * ui_HeartRangeLabel;
extern lv_obj_t * ui_HeartImage;
extern lv_obj_t * ui_bpmzhi;
extern lv_obj_t * ui_HeartSpinner;
extern lv_obj_t * ui_BloodOxygenPanel;
extern lv_obj_t * ui_bleed1;
extern lv_obj_t * ui_blood_fill;
extern lv_obj_t * ui_bleed2;
extern lv_obj_t * ui_HeartChartPanel;
extern lv_obj_t * ui_HeartChart;
extern lv_obj_t * ui_shijain1;
extern lv_obj_t * ui_shujian2;
extern lv_obj_t * ui_shijian3;
extern lv_obj_t * ui_shijiansi;
extern lv_obj_t * ui_zong3;
extern lv_obj_t * ui_shijian5;
extern lv_obj_t * ui_zong2;
extern lv_obj_t * ui_zong1;
extern lv_obj_t * ui_zong0;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_MAXnumLabel;
extern lv_obj_t * ui_MINNUMLabel;
extern void ui_event_HealthMeasureBtn(lv_event_t * e);
extern lv_obj_t * ui_HealthMeasureBtn;
extern lv_obj_t * ui_MeasureBtnLabel;
extern lv_obj_t * ui_MeasureIconPanel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

