// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: smartwatch

#ifndef _SMARTWATCH_UI_H
#define _SMARTWATCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_ScreenHome.h"
#include "screens/ui_ScreenHealth.h"
#include "screens/ui_ScreenSport.h"
#include "screens/ui_ScreenWeather.h"
#include "screens/ui_ScreenCall.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * secintro_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * minintro_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * hourintro_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * dots_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * blood1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * blood2_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * heart_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * sportarcenter_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * weathermainenter_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * forecastcardenter_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * weathericonfloat_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * homegroupfade_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * homenaventer_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * animhealthtopin_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bg4_png);    // assets/bg4.png
LV_IMG_DECLARE(ui_img_weather_sun_png);    // assets/weather_sun.png
LV_IMG_DECLARE(ui_img_flash_png);    // assets/flash.png
LV_IMG_DECLARE(ui_img_clockwise_sec_png);    // assets/clockwise_sec.png
LV_IMG_DECLARE(ui_img_clockwise_min_png);    // assets/clockwise_min.png
LV_IMG_DECLARE(ui_img_clockwise_hour_png);    // assets/clockwise_hour.png
LV_IMG_DECLARE(ui_img_843332074);    // assets/温度.png
LV_IMG_DECLARE(ui_img_545021016);    // assets/湿度.png
LV_IMG_DECLARE(ui_img_step_png);    // assets/step.png
LV_IMG_DECLARE(ui_img_1154559383);    // assets/电话- icon-copy.png
LV_IMG_DECLARE(ui_img_623432142);    // assets/运动1.png
LV_IMG_DECLARE(ui_img_heart_png);    // assets/heart.png
LV_IMG_DECLARE(ui_img_1684792934);    // assets/天气 (1).png
LV_IMG_DECLARE(ui_img_screen_background_320x240_png);    // assets/screen_background_320x240.png
LV_IMG_DECLARE(ui_img_wave2_png);    // assets/wave2.png
LV_IMG_DECLARE(ui_img_wave1_png);    // assets/wave1.png
LV_IMG_DECLARE(ui_img_1349814123);    // assets/开始按钮.png
LV_IMG_DECLARE(ui_img_1197078990);    // assets/电池-01.png
LV_IMG_DECLARE(ui_img_616669363);    // assets/跑步.png
LV_IMG_DECLARE(ui_img_1657355558);    // assets/左箭头.png
LV_IMG_DECLARE(ui_img_375917039);    // assets/右箭头.png
LV_IMG_DECLARE(ui_img_1389843189);    // assets/心率.png
LV_IMG_DECLARE(ui_img_1814031685);    // assets/卡路里-copy.png
LV_IMG_DECLARE(ui_img_1611373906);    // assets/时钟.png
LV_IMG_DECLARE(ui_img_482543466);    // assets/位置.png
LV_IMG_DECLARE(ui_img_1772208564);    // assets/多云.png
LV_IMG_DECLARE(ui_img_942679780);    // assets/天晴.png
LV_IMG_DECLARE(ui_img_2087202441);    // assets/晴转雨.png
LV_IMG_DECLARE(ui_img_1607374796);    // assets/晴转多云.png
LV_IMG_DECLARE(ui_img_1369692798);    // assets/彩虹转多云.png
LV_IMG_DECLARE(ui_img_1225357782);    // assets/大雨.png
LV_IMG_DECLARE(ui_img_1840017345);    // assets/雷阵雨.png
LV_IMG_DECLARE(ui_img_call_png);    // assets/call.png

// FONTS
LV_FONT_DECLARE(ui_font_H1);
LV_FONT_DECLARE(ui_font_SmileySans26);
LV_FONT_DECLARE(ui_font_Number_big);
LV_FONT_DECLARE(ui_font_Number_extra);
LV_FONT_DECLARE(ui_font_Smil16);
LV_FONT_DECLARE(ui_font_Subtitle);
LV_FONT_DECLARE(ui_font_Title);
LV_FONT_DECLARE(ui_font_Smil16);
LV_FONT_DECLARE(ui_font_H1);
LV_FONT_DECLARE(ui_font_Number_big);
LV_FONT_DECLARE(ui_font_Number_extra);
LV_FONT_DECLARE(ui_font_SmileySans26);
LV_FONT_DECLARE(ui_font_Subtitle);
LV_FONT_DECLARE(ui_font_Title);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
