// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: smartwatch

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void home_screen_loaded_event(lv_event_t * e);
void home_screen_unloaded_event(lv_event_t * e);
void health_screen_unloaded_event(lv_event_t * e);
void health_measure_btn_event(lv_event_t * e);
void health_measure_toggle_cb(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
