// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: smartwatch

#include "ui.h"

void home_screen_loaded_event(lv_event_t * e)
{
	// Your code here
}

void home_screen_unloaded_event(lv_event_t * e)
{
	// Your code here
}

void health_screen_unloaded_event(lv_event_t * e)
{
	// Your code here
}

void health_measure_btn_event(lv_event_t * e)
{
	// Your code here
}

void health_measure_toggle_cb(lv_event_t * e)
{
	// Your code here
}
